// server/routes/aqgQuizRoutes.js
const express = require("express");
const router = express.Router();
const Quiz = require("../models/Quiz");
const { protect } = require("../middleware/authMiddleware");

// Save quiz generated by AI
router.post("/save", protect, async (req, res) => {
  try {
    const { title, questions, isPublic } = req.body;

    if (!title || !questions || !questions.length) {
      return res.status(400).json({ message: "Missing title or questions" });
    }

    const quiz = await Quiz.create({
      title,
      description: "AI generated quiz",
      isPublic: isPublic || false,
      questions,
      createdBy: req.user._id,
    });

    res.json({ success: true, quiz });
  } catch (err) {
    console.error("Error saving AI quiz:", err);
    res.status(500).json({ message: "Server error while saving quiz" });
  }
});

module.exports = router;
